version: '3'
services:

  db:
    image: postgres:14.2
    hostname: postgres-host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  app-backend:
    build:
      context: ../../src/backend/web-chat
      dockerfile: Dockerfile
    image: app-backend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
      - KAFKA_BROKER=kafka:29092
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      - db

  app-frontend:
    build:
      context: ../../src/frontend/web-chat
      dockerfile: Dockerfile
    image: app-frontend
    environment:
      - REACT_APP_SERVICE_URL=localhost:9090
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - app-backend